version: 2.1

browsers_unit_tests:
  steps:
    - checkout
    - node/with-cache:
      steps:
        - run: npm install
        - run: npm test

jobs:
  node12-browsers:
    docker:
      - image: circleci/node:12-browsers
      <<: *browsers_unit_tests

workflows:
    build-and-test:
      jobs:
        - node12-browsers
